- hosts: magare1.otselo.eu
  become: yes
  become_method: sudo
  vars:
    domain: magare.otselo.eu
    certbot_auto_renew: yes
    certbot_auto_renew_user: alek
    certbot_auto_renew_hour: 1
    certbot_auto_renew_minute: 33
    certbot_create_if_missing: no
    certbot_create_method: standalone
    certbot_admin_email: akodzhabashev@gmail.com
    certbot_create_standalone_stop_services: []
    certbot_certs:
      - domains:
        - '{{domain}}'
    certbot_install_from_source: yes
    certbot_dir: /opt/certbot
  roles:
    - geerlingguy.certbot
  tasks:
    - name: ensure auto-renewal happens at the correct port
      lineinfile:  
        path: /etc/letsencrypt/renewal/{{ domain }}.conf
        regexp: '^http01_port'
        line: http01_port = 54321

    - name: Pull certificate
      synchronize: 
        mode: pull
        src: /etc/letsencrypt/
        dest: etc-letsencrypt

- hosts: [magare2.otselo.eu,magare3.otselo.eu,magare4.otselo.eu]
  vars:
    domain: magare.otselo.eu
  tasks:
    - name: Ensure certificate directory exists
      become: yes
      become_method: sudo
      file:
        path: /etc/letsencrypt/
        state: directory
        owner: root
        group: root

    - name: Push certificate
      become: yes
      become_method: sudo
      synchronize: 
        src: etc-letsencrypt/
        dest: /etc/letsencrypt/

- hosts: magareta
  vars:
    domain: magare.otselo.eu
  tasks:
    - name: Make magare own the letsencrypt directory
      become: yes
      become_method: sudo
      file:
        path: /etc/letsencrypt
        owner: couchdb
        group: couchdb
        recurse: yes
        state: directory
