- hosts: magareta
  vars:
    couchdb_home: /opt/couchdb
    local_config_url: "http://127.0.0.1:5984/_node/couchdb@{{inventory_hostname}}/_config"
    packages: [build-essential, pkg-config, erlang, erlang-reltool, libicu-dev, libmozjs185-dev, libcurl4-openssl-dev, python-sphinx, python-sphinx-rtd-theme]
    build_dir: "/home/alek/couchdb-build" # not in temp because we run out of space
    ssl_dir: "/etc/letsencrypt/live/magare.otselo.eu"
    ssl_cacert_file: "{{ssl_dir}}/fullchain.pem"
    ssl_cert_file: "{{ssl_dir}}/cert.pem"
    ssl_key_file: "{{ssl_dir}}/privkey.pem"
  tasks:
    - name: check couchdb binary
      become: yes
      become_method: sudo 
      stat:
        path: "{{ couchdb_home }}/bin/couchdb"
      register: sym

    - name: install couchdb
      when: sym.stat.islnk is not defined
      block:
      - name: as sudo
        become: yes
        become_method: sudo
        block:
        - name: install dependencies from apt
          apt:
            name: "{{ item }}"
          with_items: "{{ packages }}"

        - name: add nodesource nodejs 10 repository
          shell: |
            curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -

        - name: install nodejs
          apt:
            name: nodejs

      - name: create build directory
        file: 
          path: "{{ build_dir }}"
          state: directory

      - name: clone latest couchdb from git
        git:
          repo: https://github.com/apache/couchdb
          dest: "{{ build_dir }}/couchdb"
          clone: yes

      - name: configure
        command: ./configure
        args:
          chdir: "{{ build_dir }}/couchdb"

      - name: make
        make:
          chdir: "{{ build_dir }}/couchdb"
        ignore_errors: yes
        register: make_result

      - name: make release
        make:
          target: release
          chdir: "{{ build_dir }}/couchdb"
        ignore_errors: yes
        register: make_result
      
      - name: ignore known documentation build failure
        fail: 
        when: make_result.failed and "cannot stat 'src/docs/build/man/apachecouchdb" not in make_result.msg
     
      - name: as sudo
        become: yes
        become_method: sudo
        block:
        - name: add couchdb user
          user:
            name: couchdb
            comment: "CouchDB Administrator"
            shell: /bin/bash
            system: yes
            group: 
            home: /opt/couchdb
            createhome: no

        - name: move build to couchdb home
          command: cp -r "{{ build_dir }}/couchdb/rel/couchdb" /opt/couchdb

        - name: make couchdb own his home
          command: chown -R couchdb:couchdb /opt/couchdb/

        - name: make couchdb directories only user and group accessible
          command: find /opt/couchdb -type d -exec chmod 0770 {} \; 

        - name: loosen couchdb config directories permissions
          file: 
            path: "/opt/couchdb/etc/{{ item }}"
            mode: 0644 
          with_items: [default.d, local.d]

    - name: fix couchdb instance name
      become: yes
      template:
        src: vm.args.j2
        dest: /opt/couchdb/etc/vm.args
        owner: couchdb
        group: couchdb
      notify:
        restart couchdb

    - name: install libcap2 from apt
      become: yes
      apt:
        name: libcap2-bin 

    - name: allow couchdb to access ports < 1024
      become: yes
      command: setcap 'cap_net_bind_service=+ep' /opt/couchdb/erts-8.2.1/bin/beam.smp

    - name: configure SSL
      become: yes
      ini_file:
        path: /opt/couchdb/etc/local.ini
        section: '{{item.section}}'
        option: '{{item.option}}'
        value: '{{item.value}}'
        owner: couchdb
        group: couchdb
      with_items:
        - { section: daemons, option: httpsd, value: '{chttpd, start_link, [https]}' }
        - { section: ssl, option: cert_file, value: '{{ ssl_cert_file }}' }
        - { section: ssl, option: key_file, value: '{{ ssl_key_file }}' }
        - { section: ssl, option: cacert_file, value: '{{ ssl_cacert_file }}' }
        - { section: ssl, option: port, value: '443' }
      notify:
        restart couchdb

    - name: configure vhosts
      become: yes
      ini_file:
        path: /opt/couchdb/etc/local.ini
        section: vhosts
        option: '{{item.option}}'
        value: '{{item.value}}'
        owner: couchdb
        group: couchdb
      with_items:
        - { option: magare.otselo.eu, value: '/' }
        - { option: '{{inventory_hostname}}', value: '/' }
        - { option: ':webapp.otselo.eu/bundle.js', value: '/webapps/:webapp/bundle.js' }
        - { option: ':webapp.otselo.eu', value: '/webapps/:webapp/index.html' }
      notify:
        restart couchdb

    - name: add application/x-javascript to compressible types
      become: yes
      ini_file:
        path: /opt/couchdb/etc/local.ini
        section: attachments
        option: compressible_types
        value: text/*, application/javascript, application/json, application/xml, application/x-javascript
        owner: couchdb
        group: couchdb
      notify:
        restart couchdb

    - name: configure SDA
      become: yes
      ini_file:
        path: /opt/couchdb/etc/local.ini
        section: couchdb
        option: '{{item}}'
        value: /mnt/data
        owner: couchdb
        group: couchdb
      with_items:
        - database_dir
        - view_index_dir
      notify:
        restart couchdb

        #    - name: Limit erlang ports to support clustering through the Internet
        #      become: yes
        #      template:
        #        src: sys.config.j2
        #        dest: /opt/couchdb/releases/2.2.0/sys.config
        #        owner: couchdb
        #        group: couchdb
        #      notify:
        #        restart couchdb

    - name: create couchdb systemd service file
      become: yes
      become_method: sudo
      template:
        src: couchdb.service.j2
        dest: /etc/systemd/system/couchdb.service
      notify:
        restart couchdb

    - name: start and enable couchdb systemd service
      systemd: 
        name: couchdb
        daemon_reload: yes
        enabled: yes
        state: started
      become: yes
      become_method: sudo
      register: systemd_result

    - name: give couchdb some time to start
      pause:
        seconds: 10
      when: systemd_result.changed

    - name: check root account
      uri: 
        url: "{{ local_config_url }}/admins/"
        return_content: yes
      register: root_account
      ignore_errors: true

    - name: check root account with credentials
      uri: 
        url: "{{ local_config_url }}/admins/"
        user: "{{ admin_user }}"
        password: "{{ admin_password }}"
        force_basic_auth: yes
        return_content: yes
      register: used_credentials
      when: root_account.json.error | default(false) and root_account.json.error == "unauthorized"

    - name: add root account
      uri: 
        url: "{{ local_config_url }}/admins/{{ admin_user | quote }}"
        method: PUT
        body: '"{{ admin_password | quote }}"'
      when: used_credentials is skipped and root_account.json == {}
      
    - name: check public access
      uri: 
        url: "{{ local_config_url }}/chttpd/bind_address"
        user: "{{ admin_user }}"
        password: "{{ admin_password }}"
        return_content: yes
        force_basic_auth: yes
      register: bind_address

    - name: set public access
      uri: 
        url: "{{ local_config_url }}/chttpd/bind_address"
        user: "{{ admin_user }}"
        password: "{{ admin_password }}"
        method: PUT
        body: '"0.0.0.0"'
        force_basic_auth: yes
      when: bind_address.json != '0.0.0.0'

    - name: check CORS
      uri: 
        url: "{{ local_config_url }}/httpd/enable_cors"
        user: "{{ admin_user }}"
        password: "{{ admin_password }}"
        return_content: yes
        force_basic_auth: yes
      register: enable_cors

    - name: set CORS
      when: enable_cors.json == "false"
      block:
        - name: enable CORS
          uri:
            url: "{{ local_config_url }}/httpd/enable_cors"
            user: "{{ admin_user }}"
            password: "{{ admin_password }}"
            force_basic_auth: yes
            method: PUT
            body: '"true"'

        - name: enable CORS origins
          uri:
            url: "{{ local_config_url }}/cors/origins"
            user: "{{ admin_user }}"
            password: "{{ admin_password }}"
            force_basic_auth: yes
            method: PUT
            body: '"*"'

        - name: enable CORS credentials
          uri:
            url: "{{ local_config_url }}/cors/credentials"
            user: "{{ admin_user }}"
            password: "{{ admin_password }}"
            force_basic_auth: yes
            method: PUT
            body: '"true"'

        - name: enable CORS methods
          uri:
            url: "{{ local_config_url }}/cors/methods"
            user: "{{ admin_user }}"
            password: "{{ admin_password }}"
            force_basic_auth: yes
            method: PUT
            body: '"GET, PUT, POST, HEAD, DELETE"'

        - name: enable CORS headers
          uri:
            url: "{{ local_config_url }}/cors/headers"
            user: "{{ admin_user }}"
            password: "{{ admin_password }}"
            force_basic_auth: yes
            method: PUT
            body: '"accept, authorization, content-type, origin, referer, x-csrf-token"'

    - name: can ping
      uri:
        url: "http://{{ ansible_default_ipv4.address }}:5984"
        return_content: yes
      register: ping_answer

    - name: ping answer matches format
      fail:
      when: ping_answer.json.couchdb != "Welcome"

    - name: remove build directory 
      file: 
        path: "{{ build_dir }}"
        state: absent
  handlers:
    - name: Restart couchdb service
      become: yes
      become_method: sudo
      systemd:
        name: couchdb
        state: restarted
      ignore_errors: true
      listen: restart couchdb

    - name: Give couchdb time to get back up
      pause:
        seconds: 3
      listen: restart couchdb
