- hosts: magareta
  become: yes
  tasks:
    - name: make a sudo group
      group: 
        name: sudo
        state: present

    - name: allow group sudo to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL = (root) NOPASSWD:ALL'
        validate: 'visudo -cf %s'

    - name: make user alek
      user:
        name: alek
        shell: /bin/bash
        groups: sudo
        append: yes
        password: '{{admin_password}}' # necessary otherwise user is locked and we cannot ssh into it
        update_password: on_create

    - name: make sure alek is authenticated via key
      authorized_key:
        user: alek
        key: '{{ item }}'
      with_file:
        - id_rsa_magare.pub

    - name: configure sshd
      template:
        src: sshd_config.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: "0644"
        validate: '/usr/sbin/sshd -T -f %s'
      notify: restart sshd
    - name: install monit
      apt: 
        name: monit

    - name: configure monit
      template:
        src: monit_config.j2
        dest: /etc/monit/conf.d/monit_config
      notify: restart monit

    - name: enable and start monit
      systemd:
        name: monit
        daemon_reload: yes
        enabled: yes
        state: started
  handlers:
    - name: restart sshd
      service: 
        name: sshd
        state: restarted

    - name: restart monit
      systemd:
        name: monit
        state: restarted

