- hosts: magareta
  become: yes
  tasks:
    - name: get sda size
      parted:
        device: /dev/sda
        unit: GiB
      register: sda_info

    - name: expect disk to be around 1TB
      fail:
      when: sda_info.disk.size < 900 or sda_info.disk.size > 1100

    - name: partition sda into one partition
      parted:
        device: /dev/sda
        number: 1
        state: present
      register: partition_result

    - name: give disk some time to sync
      pause:
        seconds: 10
      when: partition_result.changed

    - name: make a filesystem on sda1
      filesystem:   
        fstype: btrfs
        dev: /dev/sda1

    - name: make mount directory
      file:
        path: /mnt/data
        state: directory
        owner: couchdb
        group: couchdb

    # sometimes have to execute again to fix mount directory permissions
    - name: mount /dev/sda1 to /mnt/data on boot
      blockinfile:
        block: "/dev/sda1 /mnt/data btrfs defaults 0 2"
        path: /etc/fstab
      notify: reboot

    - name: install monit
      apt: 
        name: monit

    - name: configure monit
      template:
        src: monit_config.j2
        dest: /etc/monit/conf.d/monit_config
      notify: restart monit

    - name: enable and start monit
      systemd:
        name: monit
        daemon_reload: yes
        enabled: yes
        state: started

  handlers:
    - name: reboot
      command: systemctl reboot

    - name: restart monit
      systemd:
        name: monit
        state: restarted

