- hosts: magare2.otselo.eu
  become: yes
  tasks:
    - name: get sda size
      parted:
        device: /dev/sda
        unit: GiB
      register: sda_info

    - name: expect disk to be around 1TB
      fail:
      when: sda_info.disk.size < 900 or sda_info.disk.size > 1100

    - name: make sure log2ram is disabled
      systemd:
        name: log2ram
        enabled: false
      notify: reboot

    - name: make 1GiB logs partition
      parted:
        device: /dev/sda
        number: 1
        state: present
        part_end: 1GiB
      register: partition_result1

    - name: make data partition
      parted:
        device: /dev/sda
        number: 2
        state: present
        part_start: 1GiB
      register: partition_result2

    - name: give disk some time to sync
      pause:
        seconds: 10
      when: partition_result1.changed or partition_result2.changed

    - name: make filesystems on sda1 and sda2
      filesystem:   
        fstype: btrfs
        dev: /dev/{{item}}
      with_items: [sda1, sda2]

    - name: make mount directory
      file:
        path: /mnt/data
        state: directory
        owner: couchdb
        group: couchdb

    # have to run it twice to set the correct permissions
    - name: mount /dev/sda1 to /var/log on boot
      blockinfile:
        marker: "# {mark} /var/log ANSIBLE MANAGED BLOCK"
        block: "/dev/sda1 /var/log btrfs defaults 0 2"
        path: /etc/fstab
      notify: reboot
    - name: mount /dev/sda2 to /mnt/data on boot
      blockinfile:
        marker: "# {mark} /mnt/data ANSIBLE MANAGED BLOCK"
        block: "/dev/sda2 /mnt/data btrfs defaults 0 2"
        path: /etc/fstab
      notify: reboot

    - name: install monit
      apt: 
        name: monit

    - name: configure monit
      template:
        src: monit_config.j2
        dest: /etc/monit/conf.d/monit_config
      notify: restart monit

    - name: enable and start monit
      systemd:
        name: monit
        daemon_reload: yes
        enabled: yes
        state: started

    - name: install rrdtool # used for manual graphing of collectd
      apt:
        name: rrdtool

  handlers:
    - name: reboot
      command: systemctl reboot

    - name: restart monit
      systemd:
        name: monit
        state: restarted
