# TODO if databases contains databases not defined here, explode with error
- name: get databases
  local_action:
    module: uri
    url: 'https://{{magare_hostname}}/_all_dbs'
    return_content: yes
  register: databases

- name: install validators
  include_tasks: install-validator.yaml
  loop: "{{validators}}"
  loop_control:
    loop_var: validator
