- import_tasks: couchdb.yaml
  vars:
    couchdb_home: /opt/couchdb
    local_config_url: "http://127.0.0.1:5984/_node/couchdb@{{inventory_hostname}}/_config"
    packages: [build-essential, pkg-config, erlang, erlang-reltool, libicu-dev, libmozjs185-dev, libcurl4-openssl-dev, python-sphinx, python-sphinx-rtd-theme]
    build_dir: "/home/alek/couchdb-build" # not in temp because we run out of space
    ssl_dir: "/etc/letsencrypt/live/magare.otselo.eu"
    ssl_cacert_file: "{{ssl_dir}}/fullchain.pem"
    ssl_cert_file: "{{ssl_dir}}/cert.pem"
    ssl_key_file: "{{ssl_dir}}/privkey.pem"
    nodejs_version: 10.x
    nodejs_install_npm_user: root

- import_tasks: couchdb-cluster.yaml
  when: magare_name == 'magare1'
  vars:
    couchdb_url: "http://127.0.0.1:5984"
    couchdb_nodes_url: "http://127.0.0.1:5986"

- import_tasks: couchdb-validators.yaml
  vars:
    magare_hostname: magare.otselo.eu
    validators:
      - { name: authenticated-write, tables: [ features ]}
      - { name: version-control, tables: [ features ]}
      - { name: votes, tables: [ features ]}

- import_tasks: couchdb-everyone-gets-replica-1.yaml
  tags:
    - cluster_maintenance

