- name: make a sudo group
  group: 
    name: sudo
    state: present

- name: allow group sudo to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL = (root) NOPASSWD:ALL'
    validate: 'visudo -cf %s'

- name: make admin user
  user:
    name: '{{admin_user}}'
    shell: /bin/bash
    groups: sudo
    append: yes
    password: '{{admin_password}}' # necessary otherwise user is locked and we cannot ssh into it
    update_password: on_create

- name: make sure admin user is authenticated via key
  authorized_key:
    user: '{{ admin_user }}'
    key: '{{ item }}'
  with_file:
    - id_rsa_magare.pub

- name: configure sshd
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
    validate: '/usr/sbin/sshd -T -f %s'
  notify: restart sshd

- name: change hostname
  block:
    - name: set hostname
      hostname: 
        name: '{{magare_name}}'
      notify: Restart machine

    - name: modify /etc/hosts
      become: yes
      lineinfile:
        path: /etc/hosts
        regexp: '^127.0.0.1'
        line: '127.0.0.1 localhost {{magare_name}} {{ansible_host}} {{inventory_hostname}}'
      notify: Restart machine

- name: install monit
  apt: 
    name: monit

- name: configure monit
  template:
    src: monit_config.j2
    dest: /etc/monit/conf.d/monit_config
  notify: restart monit

- name: enable and start monit
  systemd:
    name: monit
    daemon_reload: yes
    enabled: yes
    state: started
