- import_tasks: magare.yaml
  become: yes
- import_tasks: magare-sda.yaml
  become: yes
# TODO wait for systems to reboot, then repeat last command
- import_tasks: magare-sda.yaml
  become: yes

- name: setup nftables
  import_tasks: nftables.yaml
  become: yes
  tags:
    - firewall

- import_tasks: certbot-master.yaml
  when: magare_name == "magare1"
  become: yes

- import_tasks: certbot.yaml

- import_tasks: magare-haproxy.yaml
  become: yes
  vars:
    - domain: magare.otselo.eu

- import_tasks: magare-collectd.yaml
  vars:
    - couchdb_system_monitor_dir: /opt/couchdb-system-monitor
    - couchdb_url: "http://127.0.0.1:5984"
  tags:
    - collectd
