- name: restart sshd
  service: 
    name: sshd
    state: restarted

- name: restart monit
  systemd:
    name: monit
    state: restarted

- name: reboot
  command: systemctl reboot

- name: restart haproxy
  systemd:
    name: haproxy
    state: restarted

- name: restart collectd
  become: yes
  systemd:
    name: collectd
    state: restarted

- name: Restart nftables service
  become: yes
  systemd:
    daemon_reload: yes
    state: restarted
    name: nftables
    enabled: yes 

- name: Restart machine
  become: yes
  reboot:

- name: restart graphite
  become: yes
  systemd:
    daemon_reload: yes
    state: restarted
    name: graphite
    enabled: yes 

- name: restart uwsgi
  become: yes
  systemd:
    state: restarted
    name: uwsgi
    enabled: yes 


    
